### ISSUE TITLE
Add Esc to step out from mark mode

### ISSUE THREAD

**Issue by gizak** [hiro-sun/vscode-emacs#18]
This is actually a feature request.

vscode-emacs works great, but there is a problem - when I accidentally entered mark mode (with the `Yank` text appearing on status bar) and I want to quit the mark-yank workflow, I have to actually copy or cut the selection to return to normal mode. Did I miss something?

Maybe we could use Esc to break the workflow like in search mode?

**Comment by sammy44nts** [comment]
When text is Yanked, vscode-emacs automatically enter in Mark mode in order to copy emacs behavior.

`C-g` is supposed to exit Mark mode. Doesn't it work?

**Comment by gizak** [comment]
My bad, It is working now. The `C-g` key mapping was override on my machine. 

However there is another issue - When I selected some text, then `M-w` and `C-y`, the copy and paste behaviour was correct but after the operation I found I was still in `Yank` mode. 

Is it a intended behaviour? In Emacs it just gets back to normal mode since the operation finished.

**Comment by sammy44nts** [comment]
You are right, I tested on emacs in Bash on Windows during developments and the behavior was wrong. It entered Mark mode after a `Yank` operation. My bad, I'll correct this wrong behavior since emacs on Linux does not enter in Mark mode after a `Yank` operation.

Thank you very much for your feedback :+1: 

Another way to exit Mark mode is to type `C-space` again. Does it work for you?
